const KomponenBelajar = [
    {
        id: 1,
        imgSrc: "/images/layanan/layanan1.png",
        title: "Komponen Fundamental Learning",
        imgAlt: "Zenius Center",
        text: "Layanan 1",
    },
    {
        id: 2,
        imgSrc: "/images/layanan/layanan2.png",
        title: "Kelas Offline Yang Interaktif dan Nyaman",
        imgAlt: "Zenius Center",
        text: "Layanan 2",
    },
    {
        id: 3,
        imgSrc: "/images/layanan/layanan3.png",
        title: "Pendalaman materi pelajaran sekolah",
        imgAlt: "Zenius Center",
        text: "Layanan 3",
    },
    {
        id: 4,
        imgSrc: "/images/layanan/layanan4.png",
        imgAlt: "Layanan 4",
        title: "Akses ke platform digital Zenius",
        text: "Layanan 4",
    },
    {
        id: 5,
        imgSrc: "/images/layanan/layanan5.png",
        imgAlt: "Layanan 5",
        title: "Buku pelajaran Kurikulum Merdeka",
        text: "Layanan 5",
    },
    {
        id: 6,
        imgSrc: "/images/layanan/layanan6.png",
        imgAlt: "Layanan 6",
        title: "Ulas Cerdas Model",
        text: "Layanan 6",
    },
    {
        id: 7,
        imgSrc: "/images/layanan/layanan6.png",
        imgAlt: "Layanan 6",
        title: "ZenCore",
        text: "Layanan 6",
    },
    {
        id: 8,
        imgSrc: "/images/layanan/layanan6.png",
        imgAlt: "Layanan 6",
        title: "TryOut berkala secara daring",
        text: "Layanan 6",
    },{
        id: 9,
        imgSrc: "/images/layanan/layanan6.png",
        imgAlt: "Layanan 6",
        title: "Analisis Prestasi Rapor",
        text: "Layanan 6",
    },{
        id: 10,
        imgSrc: "/images/layanan/layanan6.png",
        imgAlt: "Layanan 6",
        title: "Tes Psiko-Kognitif",
        text: "Layanan 6",
    },{
        id: 11,
        imgSrc: "/images/layanan/layanan6.png",
        imgAlt: "Layanan 6",
        title: "Buku HAJAR (Bahan Belajar)",
        text: "Layanan 6",
    },{
        id: 12,
        imgSrc: "/images/layanan/layanan6.png",
        imgAlt: "Layanan 6",
        title: "TryOut persiapan SNBT online",
        text: "Layanan 6",
    },{
        id: 13,
        imgSrc: "/images/layanan/layanan6.png",
        imgAlt: "Layanan 6",
        title: "Konsultasi belajar",
        text: "Layanan 6",
    },{
        id: 14,
        imgSrc: "/images/layanan/layanan6.png",
        imgAlt: "Layanan 6",
        title: "Pendampingan persiapan tes dan ujian",
        text: "Layanan 6",
    },{
        id: 15,
        imgSrc: "/images/layanan/layanan6.png",
        imgAlt: "Layanan 6",
        title: "Persiapan kampus impian",
        text: "Layanan 6",
    },
]

export default KomponenBelajar;
